server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://some_address:5432/y_project_2023
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
    